name: Add a new sound
description: Adds your sounds to the Click Sounds repository
labels: []
body: 
  - type: markdown
    attributes:
      value: "# Click Sounds Request"
  - type: textarea
    id: zip
    attributes:
      label: Add Pack
      description: Add your click sound files here in a **COMPRESSED *ZIP* FILE**, NOTHING ELSE (ZIP FILE MUST INCLUDE A pack.json FILE)
      placeholder: Input files here
    validations:
      required: true
  - type: textarea
    id: issuedesc
    attributes:
      label: Any comments for the moderators?
      description: Optional
      placeholder: Type a message for the Index Moderators here (optional)
    validations:
      required: false
